alter table if exists leaic_crosswalk
    add column if not exists fstate text,
    add column if not exists fcounty text,
    add column if not exists fplace text,
    add column if not exists fips_st text,
    add column if not exists fips_county text,
    add column if not exists fips text,
    add column if not exists ori9 text,
    add column if not exists ori7 text,
    add column if not exists name text,
    add column if not exists ua text,
    add column if not exists statename text,
    add column if not exists countyname text,
    add column if not exists uaname text,
    add column if not exists partof text,
    add column if not exists agcytype text,
    add column if not exists subtype1 text,
    add column if not exists subtype2 text,
    add column if not exists govid text,
    add column if not exists lg_name text,
    add column if not exists address_name text,
    add column if not exists address_str1 text,
    add column if not exists address_str2 text,
    add column if not exists address_city text,
    add column if not exists address_state text,
    add column if not exists address_zip text,
    add column if not exists report_flag text,
    add column if not exists csllea08_id text,
    add column if not exists lemas_id text,
    add column if not exists u_stateno text,
    add column if not exists u_cnty text,
    add column if not exists u_popgrp text,
    add column if not exists u_tpop text,
    add column if not exists lg_population text,
    add column if not exists csllea_sub text,
    add column if not exists comment text,
    add column if not exists intptlat text,
    add column if not exists intptlong text,
    add column if not exists congdist1 text,
    add column if not exists congdist2_18 text,
    add column if not exists distname text,
    add column if not exists source_csllea2008 text,
    add column if not exists source_ucr2010 text,
    add column if not exists source_ucr2011 text,
    add column if not exists source_ucr2012 text,
    add column if not exists source_ncic2012 text,
    add column if not exists source_vendor text;

create index if not exists idx_leaic_fplace on leaic_crosswalk (fplace);
create index if not exists idx_leaic_fips on leaic_crosswalk (fips);
create index if not exists idx_leaic_zip on leaic_crosswalk (address_zip);
create index if not exists idx_leaic_citystate on leaic_crosswalk (address_city, address_state);
